export interface ProcessingOptions {
  cropPosition: number;
  aspectRatio: "16:9" | "9:16";
  language?: string;
  burnSubtitles: boolean;
  subtitleFont?: string;
}

export interface VideoFile {
  url: string;
  type: string;
  name: string;
}

export interface SubtitleOptions {
  fontSize: number;
  color: string;
  borderSize: number;
  borderColor: string;
  verticalPosition: number;
  font: string;
}

export const SUBTITLE_FONTS = [
  "kcalBrecapS",
  "ralugeRnamokifA",
  "ralugeRaksalA",
  "dloBsuedamA",
  "ralugeRsuedamA",
  "dloBminanA",
  "thgiLminanA",
  "ralugeRminanA",
  "ralugeRtrA",
  "dloBsogarapsA",
  "thgiLsogarapsA",
  "ralugeRsogarapsA",
  "dloBaluzA",
  "ralugeRaluzA",
  "dloBvotrekoB",
  "muideMvotrekoB",
  "ralugeRvotrekoB",
  "hcaitaPhpargilaC",
  "dloBniapmaC",
  "thgiLniapmaC",
  "ralugeRniapmaC",
  "ralugeRaloyarC",
  "alilaD",
  "akimaniD",
  "muideMakimaniD",
  "eniltuOnIevirD",
  "pirtogE",
  "dloBpirtogE",
  "dloBqemE",
  "ralugeRqemE",
  "ralugeRtamlidnE",
  "kcalByzatxE",
  "dloByzatxE",
  "thgiLyzatxE",
  "kcalBmirtxE",
  "dloBmirtxE",
  "ralugeRmirtxE",
  "ralugeRcilF",
  "dloBayaG",
  "thgiLafariG",
  "ralugeRafariG",
  "dloBemroG",
  "thgiLemroG",
  "ralugeRemroG",
  "dloBweNasadaH",
  "thgiLweNasadaH",
  "ralugeRweNasadaH",
  "kcalBngiseDmiaH",
  "dloBngiseDmiaH",
  "ralugeRateyrneH",
  "ralugeRleamhsI",
  "dloBlearsI",
  "ralugeRlearsI",
  "ralugeRobmaJ",
  "dloBrekoJ",
  "thgiLrekoJ",
  "ralugeRrekoJ",
  "dloBazirpaK",
  "ralugeRazirpaK",
  "ralugeRapilK",
  "dloBraddiL",
  "ralugeRraddiL",
  "ralugeRnapizraM",
  "ralugeRanilodnaM",
  "kcalBhsekaraM",
  "dloBhsekaraM",
  "ralugeRhsekaraM",
  "dloBaraMraM",
  "ralugeRaraMraM",
  "napizraM",
  "dloBnapizraM",
  "muideMnapizraM",
  "ralugeRsufDtanohceM",
  "ralugeRafineM",
  "ralugeRotiksoM",
  "dloBvadaN",
  "thgiLvadaN",
  "ralugeRvadaN",
  "dloBakihseN",
  "thgiLakihseN",
  "ralugeRakihseN",
  "kcalBmumitpO",
  "dloBmumitpO",
  "ralugeRmumitpO",
  "ralugeRynagrO",
  "ralugeRraksO",
  "dloBlliFakinaP",
  "ralugeRlliFakinaP",
  "dloBtuOakinaP",
  "ralugeRtuOakinaP",
  "thgiLlepliP",
  "ralugeRlepliP",
  "ralugeRretnolP",
  "israPvegeR",
  "dloBisraPvegeR",
  "dloBrugihS",
  "ralugeRrugihS",
  "dloBrecapS",
  "ralugeRrecapS",
  "ralugeRyzanekhsAmatS",
  "ralugeRydarafSmatS",
  "ralugeRamgitS",
  "ralugeRoidutS",
  "dloBtirfaT",
  "ralugeRtirfaT",
  "ralugeRnilvaT",
  "ralugeRaveT",
  "dloBzeraHterezoT",
  "ralugeRzeraHterezoT",
  "dloBanilopmarT",
  "thgiLanilopmarT",
  "ralugeRanilopmarT",
  "ralugeRatogiZ",
] as const;
