export interface ProcessingOptions {
  cropPosition: number;
  aspectRatio: "16:9" | "9:16";
  language?: string;
  burnSubtitles: boolean;
  subtitleFont?: string;
}

export interface VideoFile {
  url: string;
  type: string;
  name: string;
}

export interface SubtitleOptions {
  fontSize: number;
  color: string;
  borderSize: number;
  borderColor: string;
  verticalPosition: number;
  font: string;
}

export const SUBTITLE_FONTS = [
  "AfikomanRegular",
  "AlaskaRegular",
  "AmadeusBold",
  "AmadeusRegular",
  "AnanimBold",
  "AnanimLight",
  "AnanimRegular",
  "ArtRegular",
  "AsparagosBold",
  "AsparagosLight",
  "AsparagosRegular",
  "AzulaBold",
  "AzulaRegular",
  "BokertovBold",
  "BokertovMedium",
  "BokertovRegular",
  "CaligraphPatiach",
  "CampainBold",
  "CampainLight",
  "CampainRegular",
  "CrayolaRegular",
  "Dalila",
  "Dinamika",
  "DinamikaMedium",
  "DriveInOutline",
  "Egotrip",
  "EgotripBold",
  "EmeqBold",
  "EmeqRegular",
  "EndilmatRegular",
  "ExtazyBlack",
  "ExtazyBold",
  "ExtazyLight",
  "ExtrimBlack",
  "ExtrimBold",
  "ExtrimRegular",
  "FlicRegular",
  "GayaBold",
  "GirafaLight",
  "GirafaRegular",
  "GormeBold",
  "GormeLight",
  "GormeRegular",
  "HadasaNewBold",
  "HadasaNewLight",
  "HadasaNewRegular",
  "HaimDesignBlack",
  "HaimDesignBold",
  "HenryetaRegular",
  "IshmaelRegular",
  "IsraelBold",
  "IsraelRegular",
  "JamboRegular",
  "JokerBold",
  "JokerLight",
  "JokerRegular",
  "KaprizaBold",
  "KaprizaRegular",
  "KlipaRegular",
  "LiddarBold",
  "LiddarRegular",
  "MandolinaRegular",
  "MarakeshBlack",
  "MarakeshBold",
  "MarakeshRegular",
  "MarMaraBold",
  "MarMaraRegular",
  "Marzipan",
  "MarzipanBold",
  "MarzipanMedium",
  "MechonatDfusRegular",
  "MenifaRegular",
  "MoskitoRegular",
  "NadavBold",
  "NadavLight",
  "NadavRegular",
  "NeshikaBold",
  "NeshikaLight",
  "NeshikaRegular",
  "OptimumBlack",
  "OptimumBold",
  "OptimumRegular",
  "OrganyRegular",
  "OskarRegular",
  "PanikaFillBold",
  "PanikaFillRegular",
  "PanikaOutBold",
  "PanikaOutRegular",
  "PilpelLight",
  "PilpelRegular",
  "PlonterRegular",
  "RegevParsi",
  "RegevParsiBold",
  "ShigurBold",
  "ShigurRegular",
  "SpacerBlack",
  "SpacerBold",
  "SpacerRegular",
  "StamAshkenazyRegular",
  "StamSfaradyRegular",
  "StigmaRegular",
  "StudioRegular",
  "TafritBold",
  "TafritRegular",
  "TavlinRegular",
  "TevaRegular",
  "TozeretHarezBold",
  "TozeretHarezRegular",
  "TrampolinaBold",
  "TrampolinaLight",
  "TrampolinaRegular",
  "ZigotaRegular",
] as const;
